### ISSUE TITLE
Period at start of the mod name

### ISSUE THREAD

**Issue by EmeraldLoc** [EmilyEmmi/MarioHunt#2]
<img width="24" alt="Screenshot 2023-07-01 at 6 18 31 PM" src="https://github.com/EmilyEmmi/MarioHunt/assets/86802223/6a7970d2-ca01-49e2-b0dd-b4bfe7195a17">
<img width="108" alt="Screenshot 2023-07-01 at 6 21 06 PM" src="https://github.com/EmilyEmmi/MarioHunt/assets/86802223/c68cad37-13c9-4900-b3cf-fc5951c25dde">

Think the issue is pretty self explanatory

**Comment by EmilyEmmi** [comment]
I've gotten tons of comments about this; it's to make the mod load first. Otherwise, mods that use the MarioHunt API would break. Thank you!
