### ISSUE TITLE
/skip bug

### ISSUE THREAD

**Issue by ChainChomp5040** [EmilyEmmi/MarioHunt#7]
i was playing minihunt and n64 and i both did /skip at the same time and it said 1/2 have voted twice
you can see at 25:05 in this video https://www.youtube.com/watch?v=MKFfIATD4Gw

**Comment by EmilyEmmi** [comment]
Consequence of how the netcode works- it adds 1 to total votes on each end, then updates the count, but then one of the votes gets "eaten" as a result. Thankfully, I've just thought of a way to fix this. Thanks for the report!
